def Rules():
    print('Welcome to HANGMAN Game')
    print('Objective : Guess the English word randomly generated by the game')
    print('You get 7 lives to guess the word')
    print('Each time when you enter any letter if it is present in the word then\nall the instences of that letter will be updated else it would cost you a life')
    print('You can enter the letter in any case ')
    print('If you input the string then only the first letter would be consider for the game')
    input("\nPress any key to continue ")
